FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Graspe

Api for Learning platform

## Organization's Referral System  [/organizations/1/referral-system]

### Create referral system [POST]

Create referral system for specific organization

+ `rewards_type` : `1` for subscription months, `2` for prize
+ `prize_image_url` and `prize_description` is `optional`

+ Request (application/json)
        
        data:[
                {
                    "rewards_type": 1,
                    "referral_points": 3,
                    "subscription_months_count": 2
                },
                {
                    "rewards_type": 2,
                    "referral_points": 300,
                    "prize_title": "iPhone",
                    "prize_image_url": "https://amazon.cloud/iphone.jpg",
                    "prize_description": "New iPhone"
                }
        ]
        
+ Response 200 (application/json)      

        {status:1 , msg:"The referral was successfully created."}
        
+ Response 500 (application/json)        
        
        {status:0 , msg:"The referral was not created  successfully."}      
        
+ Response 403 (application/json)        
        
        {status:0 , msg:"Only organization administrators can create referrals."}  

### Get referral system [GET]

Get referral system for specific organization

+ Response 200 (application/json)


        [
            {
                "id":1,
                "creator_id":3,
                "rewards_type":1,
                "referral_points":20,
                "prize_title":"Surprise",
                "prize_image_url":"\/prize.jpg",
                "prize_description":"description"
                "created_at":null,
                "updated_at":null
            },
            {
                "id":2,
                "creator_id":1,
                "rewards_type":2,
                "referral_points":5,
                "subscription_months_count":2,
                "image_url":null,
                "created_at":"2017-08-24 15:29:14",
                "updated_at":"2017-08-24 15:29:14"
            }
        ]
        
### Update referral system [/organizations/1/referral-system/update] 
[POST]

Update referral system for specific organization   

+ Request (application/json)
       
       data:[
                {
                    "rewards_type": 1,
                    "referral_points": 3,
                    "subscription_months_count": 2
                },
                {
                    "rewards_type": 2,
                    "referral_points": 300,
                    "prize_title": "iPhone",
                    "image_url": "https://amazon.cloud/iphone.jpg"
                }
        ]
        
+ Response 200 (application/json)        

        {status:1 , msg:"The referral was successfully updated."}
        
+ Response 500 (application/json)        

        {status:0 , msg:"The referral was not updated successfully."}       
        
+ Response 403 (application/json)        

        {status:0 , msg:"Only organization administrators can update referrals."}           
