FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Graspe

Api for Learning platform

## Organization's Referral System  [/organizations/1/referral-system]

### Create referral system [POST]

Create referral system for specific organization

+ Request (application/json)

        {
            "rewards_type": 1,
            "referral_points": 5,
            "subscription_months_count": 2,
            "prize_title": "iPhone",
            "image_url": "https://amazon.cloud/iphone.jpg"
        }
        
+ Response 201 (application/json)

        {
            "status": 1,
            "message": "The referral successfully created"
        }


### Get referral system [GET]

Get referral system for specific organization

+ Response 200 (application/json)


        [
            {
                "id":1,
                "creator_id":3,
                "rewards_type":2,
                "referral_points":20,
                "subscription_months_count":30,
                "prize_title":"Surprise",
                "image_url":"\/prize.jpg",
                "created_at":null,
                "updated_at":null
            },
            {
                "id":2,
                "creator_id":1,
                "rewards_type":1,
                "referral_points":5,
                "subscription_months_count":2,
                "prize_title":null,
                "image_url":null,
                "created_at":"2017-08-24 15:29:14",
                "updated_at":"2017-08-24 15:29:14"
            }
        ]